import {type RouteRecordRaw} from 'vue-router';
const routes :RouteRecordRaw[] = [
    {
        path:'/jssection',
        name:'jssection',
        component:()=>import("@/views/JsSection.vue"),
        meta:{title:'js篇'},
        redirect:'/jssection/virtual-scroll-list',
        children:[
            {
                path:'router-switch-transition',
                name:'router-switch-transition',
                redirect:{
                    name:'router-switch1'
                },
                component:()=>import("@/components/js-section/router-switch-transition.vue"),
                meta:{
                    title:''
                },
                children:[
                    {
                        path:'router-switch1',
                        name:'router-switch1',
                        component:()=>import("@/components/js-section/router-switch1.vue")
                    },
                    {
                        path:'router-switch2',
                        name:'router-switch2',
                        component:()=>import("@/components/js-section/router-switch2.vue")
                    }
                ]
            },
            {
                path:'ref-and-reactive',
                name:'ref-and-reactive',
                component:()=>import("@/components/js-section/ref-and-reactive.vue") 
            },
            {
                path:'virtual-scroll-list',
                name:'VirtualScrollList',
                meta:{
                    title:'虚拟滚动列表实现'
                },
                component:()=>import("@/components/js-section/virtual-scroll-list.vue")
            },
            {
                path:'tree-data-structure',
                name:'treeDataStructureShow',
                meta:{
                    title:'树形结构数据展示'
                },
                component:()=>import("@/components/js-section/tree-data-structure.vue")
            },
            {
                path:'debounce-and-throttle',
                name:'debounceandthrottle',
                meta:{
                    title:'防抖和节流'
                },
                component:()=>import("@/components/js-section/debounce-and-throttle.vue")
            },
            {
                path:'iterator',
                name:'iterator',
                meta:{
                    title:'防抖和节流'
                },
                component:()=>import("@/components/js-section/es6-iterator.vue")
            },
            {
                path:'destructuring',
                name:'destructuring',
                meta:{
                    title:'防抖和节流'
                },
                component:()=>import("@/components/js-section/es6-destructuring.vue")
            },
            {
                path:'jsonwebtoken',
                name:'jsonwebtoken',
                meta:{
                    title:'jwt验证权限流程'
                },
                component:()=>import("@/components/js-section/es6-jwt.vue")
            }
        ]
    }
]
export default routes;