import type { AppRouteRecordRaw } from "../types/router";
export const constantRoutes : AppRouteRecordRaw[] = [
    {
        path:'/',
        name:'Home',
        component:()=> import("@/views/Home.vue"),
        meta:{title:'首页'}
    },
    {
        path:'/formdemo',
        name:'formdemo',
        component:()=>import("@/views/FormDemo.vue"),
        meta:{title:'表单演示'}
    },
    {
        path:'/tabledemo',
        name:'tabledemo',
        component:()=>import("@/views/TableDemo.vue"),
        meta:{title:'表格演示'}
    },
    {
        path:'/dialogdemo',
        name:'dialogdemo',
        component:()=>import("@/views/Dialogdemo.vue"),
        meta:{title:'dialog演示'}
    },
    {
        path:'/selectdemo',
        name:'selectdemo',
        component:()=>import("@/views/SelectDemo.vue"),
        meta:{title:'select演示'}
    },//AllElCompnentTest
    {
        path:'/AllElCompnentTest',
        name:'AllElCompnentTest',
        component:()=>import("@/views/AllElCompnentTest.vue"),
        meta:{title:'所有组件演示'}
    },//DatePickerDemo
    {
        path:'/DatePickerDemo',
        name:'DatePickerDemo',
        component:()=>import("@/views/DatePickerDemo.vue"),
        meta:{title:'时间选择器'}
    },
    {
        path:'/Tspractice',
        name:'Tspractice',
        component:()=>import("@/views/Tspractice.vue"),
        meta:{title:'ts演示'}
    },
    {
        path:'/TspracticeTwo',
        name:'TspracticeTwo',
        component:()=>import("@/views/TspracticeTwo.vue"),
        meta:{title:'ts演示2'}
    },
    {
        path:'/TspracticeThree',
        name:'TspracticeThree',
        component:()=>import("@/views/TspracticeThree.vue"),
        meta:{title:'ts实战演示3'}
    },
    {
        path:'/TspracticeFore/:id',
        name:'TspracticeFore',
        component:()=>import("@/views/TspracticeFore.vue"),
        meta:{title:'ts实战演示4'}
    }

]